# Generated by Django 5.2.8 on 2025-11-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phone',
            table='phone',
        ),
    ]
